meaning of data encoding is >> converting the categorical data into numaric form

In [2]:
import pandas as pd
import seaborn as sns
import numpy as np
import warnings
warnings.filterwarnings('ignore')

## nominal/ohe

In [1]:
from sklearn.preprocessing import OneHotEncoder


In [5]:
df=pd.DataFrame({'status':['single','married','sep','married','sep']})

In [6]:
df

status
0   single
1  married
2      sep
3  married
4      sep

In [12]:
encoder=OneHotEncoder()

In [19]:

encoded=encoder.fit_transform(df[['status']]).toarray()

In [20]:
encoder.get_feature_names_out()

array(['status_married', 'status_sep', 'status_single'], dtype=object)

In [22]:
encoder_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [24]:
encoder.transform([['single']]).toarray()

array([[0., 0., 1.]])

#### same thing we can do using pandas.get_dummies

In [26]:
pd.concat([df,encoder_df],axis=1)

status  status_married  status_sep  status_single
0   single             0.0         0.0            1.0
1  married             1.0         0.0            0.0
2      sep             0.0         1.0            0.0
3  married             1.0         0.0            0.0
4      sep             0.0         1.0            0.0

### label encoding>> assiggn uniquelabel to categories

we can do this using map function or library

In [27]:
df

status
0   single
1  married
2      sep
3  married
4      sep

In [33]:
from sklearn.preprocessing import LabelEncoder
label_encoder=LabelEncoder()

In [34]:
encoded = label_encoder.fit_transform(df['status'])

In [35]:
encoded

array([2, 0, 1, 0, 1])

In [36]:
label_encoder.transform([['single']])

array([2])

### ordinal encoding

In [37]:
from sklearn.preprocessing import OrdinalEncoder

In [38]:
df=pd.DataFrame({"qualification":['hs','sc','ug','pg','phd']})

In [39]:
df

qualification
0            hs
1            sc
2            ug
3            pg
4           phd

In [40]:
encoder=OrdinalEncoder(categories=['hs','sc','ug','pg','phd'])

In [43]:
encoder=OrdinalEncoder()

In [44]:
encoder.fit_transform(df[['qualification']])

array([[0.],
       [3.],
       [4.],
       [1.],
       [2.]])

In [45]:
encoder.transform([['phd']])

array([[2.]])

### target guided

In [46]:
df = pd.DataFrame({
    'time': ['lunch', 'breakfast', 'dinner', 'lunch', 'breakfast', 'dinner', 'lunch', 'breakfast', 'dinner'],
    'total_bill': [120, 130, 90, 125, 150, 190, 160, 180, 189]
})


In [47]:
df

time  total_bill
0      lunch         120
1  breakfast         130
2     dinner          90
3      lunch         125
4  breakfast         150
5     dinner         190
6      lunch         160
7  breakfast         180
8     dinner         189

In [52]:
mean_price=df.groupby('time')['total_bill'].mean().to_dict()

In [54]:
df['time encoded']=df['time'].map(mean_price)

In [55]:
df

time  total_bill  time encoded
0      lunch         120    135.000000
1  breakfast         130    153.333333
2     dinner          90    156.333333
3      lunch         125    135.000000
4  breakfast         150    153.333333
5     dinner         190    156.333333
6      lunch         160    135.000000
7  breakfast         180    153.333333
8     dinner         189    156.333333